const SUCCESS = 200;
const CREATED = 201;
const NO_CONTENT = 204;
const BAD_REQUEST = 400;
const UNATHORIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const CONFLICT = 409;

module.exports = {
  BAD_REQUEST,
  SUCCESS,
  FORBIDDEN,
  CONFLICT,
  CREATED,
  NO_CONTENT,
  UNATHORIZED,
  NOT_FOUND,
};
